# main branch
version: 1.3.{build}
clone_depth: 15
image: Visual Studio 2019

branches:
   only:
     - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore CloudEvents.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet pack CloudEvents.sln
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\**\*.nupkg'
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore CloudEvents.sln --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd test\CloudNative.CloudEvents.UnitTests
  - cmd: dotnet test 
on_finish :
  # any cleanup in here
