name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-22.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v3

    # Build with .NET 6.0 SDK
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: |
        dotnet build
        dotnet test
