name: Push packages to NuGet

on:
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-18.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    # Install the .NET Core 3.1 SDK for build and test
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: |
        dotnet build -c Release
        dotnet test -c Release
        mkdir nuget

    - name: Push to NuGet
      run: |
        dotnet pack -c Release -o $PWD/nuget
        # For now, just display the NuGet packages we'd push in reality.
        ls nuget
