name: Push packages to NuGet

on:
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-18.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    # We need the .NET Core 2.1 and .NET Core 3.1 runtimes for testing
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    # Build with .NET Core 5.0 SDK
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: |
        dotnet build -c Release
        dotnet test -c Release
        mkdir nuget

    - name: Push to NuGet
      run: |
        dotnet pack -c Release -o $PWD/nuget
        for file in nuget/*.nupkg; do dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} $file; done

