name: Push packages to NuGet

on:
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-22.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v3
      with:
        submodules: true

    # Build with .NET 8.0 SDK
    # Test with .NET 6.0 and 8.0
    - name: Setup .NET 6.0 and 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
          6.0.x

    - name: Build
      run: |
        dotnet build -c Release -p:ContinuousIntegrationBuild=true
        dotnet test -c Release
        mkdir nuget

    - name: Push to NuGet
      run: |
        dotnet pack -c Release -p:ContinuousIntegrationBuild=true -o $PWD/nuget
        for file in nuget/*.nupkg; do dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} $file; done
